### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/wireframe/junc/../data/junc/processed/480_60_15'

### ISSUE THREAD

**Issue by JanineCHEN** [huangkuns/wireframe#16]
When trying to execute:
`python3 main.py --create_dataset --exp 1 --json`

I got the following error:
```
#train images: 5000
src_dir: /home/wireframe/junc/../data/pointlines save_dir: /home/wireframe/junc/../data/junc/processed
== loading raw data ==
[ |######################################################################| ][ Elapsed Time: 0:00:05 ]
== 5000 raw images data loaded ==
joblib.externals.loky.process_executor._RemoteTraceback:                 | ][ Elapsed Time: 0:00:01 ]
"""
Traceback (most recent call last):
  File "/home/.virtualenvs/wireframe/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/home/.virtualenvs/wireframe/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/.virtualenvs/wireframe/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 608, in __call__
    return self.func(*args, **kwargs)
  File "/home/.virtualenvs/wireframe/lib/python3.6/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/home/.virtualenvs/wireframe/lib/python3.6/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/wireframe/junc/datasets/utils.py", line 315, in save_ann
    os.mkdir(dir_to_save)
FileNotFoundError: [Errno 2] No such file or directory: '/home/wireframe/junc/../data/junc/processed/480_60_15'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 144, in <module>
    main()
  File "main.py", line 105, in main
    if check_dataset(opt, 'train'):
  File "main.py", line 94, in check_dataset
    create_dataset(H, split, use_mp=True); 
  File "/home/wireframe/junc/datasets/utils.py", line 417, in create_dataset
    load_data_and_save(H, src_dir=src_dir, save_dir=save_dir, filenames=filelst, use_mp = use_mp)
  File "/home/wireframe/junc/datasets/utils.py", line 349, in load_data_and_save
    for d in bar(anno))  # max_len default to 1.
  File "/home/.virtualenvs/wireframe/lib/python3.6/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/home/.virtualenvs/wireframe/lib/python3.6/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/.virtualenvs/wireframe/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
FileNotFoundError: [Errno 2] No such file or directory: '/home/wireframe/junc/../data/junc/processed/480_60_15'
```
Any idea how to fix the dir path issue? Thank you

**Comment by JanineCHEN** [comment]
Any help is highly appreciated, thank you!

**Comment by antmillar** [comment]
I had to manually create that folder root/data/junc/processed/

**Comment by zxydsd** [comment]
> 尝试执行时：
> `python3 main.py --create_dataset --exp 1 --json`
> 
> 我收到以下错误：
> 
> ```
> #train images: 5000
> src_dir: /home/wireframe/junc/../data/pointlines save_dir: /home/wireframe/junc/../data/junc/processed
> == loading raw data ==
> [ |######################################################################| ][ Elapsed Time: 0:00:05 ]
> == 5000 raw images data loaded ==
> joblib.externals.loky.process_executor._RemoteTraceback:                 | ][ Elapsed Time: 0:00:01 ]
> """
> Traceback (most recent call last):
>   File "/home/.virtualenvs/wireframe/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
>     r = call_item()
>   File "/home/.virtualenvs/wireframe/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
>     return self.fn(*self.args, **self.kwargs)
>   File "/home/.virtualenvs/wireframe/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 608, in __call__
>     return self.func(*args, **kwargs)
>   File "/home/.virtualenvs/wireframe/lib/python3.6/site-packages/joblib/parallel.py", line 256, in __call__
>     for func, args, kwargs in self.items]
>   File "/home/.virtualenvs/wireframe/lib/python3.6/site-packages/joblib/parallel.py", line 256, in <listcomp>
>     for func, args, kwargs in self.items]
>   File "/home/wireframe/junc/datasets/utils.py", line 315, in save_ann
>     os.mkdir(dir_to_save)
> FileNotFoundError: [Errno 2] No such file or directory: '/home/wireframe/junc/../data/junc/processed/480_60_15'
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "main.py", line 144, in <module>
>     main()
>   File "main.py", line 105, in main
>     if check_dataset(opt, 'train'):
>   File "main.py", line 94, in check_dataset
>     create_dataset(H, split, use_mp=True); 
>   File "/home/wireframe/junc/datasets/utils.py", line 417, in create_dataset
>     load_data_and_save(H, src_dir=src_dir, save_dir=save_dir, filenames=filelst, use_mp = use_mp)
>   File "/home/wireframe/junc/datasets/utils.py", line 349, in load_data_and_save
>     for d in bar(anno))  # max_len default to 1.
>   File "/home/.virtualenvs/wireframe/lib/python3.6/site-packages/joblib/parallel.py", line 1017, in __call__
>     self.retrieve()
>   File "/home/.virtualenvs/wireframe/lib/python3.6/site-packages/joblib/parallel.py", line 909, in retrieve
>     self._output.extend(job.get(timeout=self.timeout))
>   File "/home/.virtualenvs/wireframe/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
>     return future.result(timeout=timeout)
>   File "/home/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 432, in result
>     return self.__get_result()
>   File "/home/anaconda3/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
>     raise self._exception
> FileNotFoundError: [Errno 2] No such file or directory: '/home/wireframe/junc/../data/junc/processed/480_60_15'
> ```
> 
> 任何想法如何解决目录路径问题？谢谢

Hi, were you able to solve this issue?

**Comment by whitecrow1027** [comment]
change os.mkdir() to os.makedirs()
